### ISSUE TITLE
This might be of interest

### ISSUE THREAD

**Issue by Rad0van** [yarrick/turbomem#2]
Having old Fujitsu Siemens Amilo SI 2636 still looking for something to make that Turbo Memory usable after all the years. This is what recently poped up: https://lore.kernel.org/lkml/20201126233300.10714-1-richard@nod.at/ You may find it usable :-)

**Comment by yarrick** [comment]
That looks like a nice way to avoid having to write kernel code for the chip. But for this project the main difficulty is to understand how the chip is controlled. Writing the code to do it seems to be the easy part :)

Thanks

**Comment by Rad0van** [comment]
Are you still working on this or have abandoned it already?

**Comment by yarrick** [comment]
No real progress has been made since 2015. Reverse engineering windows drivers is quite different to what I normally do so it is not that easy to quickly resume after some time off.

I have not fully abandoned it but it is very unlikely that this effort will reach a state ready for upstreaming.
